# Generated by Django 2.0.6 on 2018-07-06 16:48

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article_opt_log',
            fields=[
                ('art_opt_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='文章操作编号')),
                ('opt_content', models.CharField(max_length=400, null=True, verbose_name='操作内容')),
                ('opt_type', models.IntegerField(choices=[(1, '浏览'), (2, '关注')], null=True, verbose_name='操作类型')),
                ('opt_time', models.DateTimeField(auto_now=True, null=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '文章操作记录',
                'verbose_name_plural': '文章操作记录',
            },
        ),
        migrations.CreateModel(
            name='articles',
            fields=[
                ('article_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='文章编号')),
                ('author', models.CharField(max_length=20, verbose_name='文章作者')),
                ('title', models.CharField(max_length=20, verbose_name='文章标题')),
                ('comment', models.CharField(max_length=200, verbose_name='摘要')),
                ('content', tinymce.models.HTMLField(max_length=20000, verbose_name='文章内容')),
                ('article_coverimg', models.ImageField(null=True, upload_to='articleimage', verbose_name='文章封面图片地址')),
                ('pushdate', models.DateTimeField(auto_now=True, verbose_name='发布时间')),
                ('is_pub', models.BooleanField(choices=[(False, '否'), (True, '是')], default=False, verbose_name='是否立即发布')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='movie_opt_log',
            fields=[
                ('mov_opt_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='视频操作编号')),
                ('opt_content', models.CharField(max_length=400, null=True, verbose_name='操作内容')),
                ('opt_type', models.IntegerField(choices=[(1, '浏览'), (2, '关注')], null=True, verbose_name='操作类型')),
                ('opt_time', models.DateTimeField(auto_now=True, null=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '视频操作记录',
                'verbose_name_plural': '视频操作记录',
            },
        ),
        migrations.CreateModel(
            name='movies',
            fields=[
                ('movie_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='视频编号')),
                ('author', models.CharField(max_length=20, verbose_name='视频作者')),
                ('title', models.CharField(max_length=20, verbose_name='视频标题')),
                ('movie_coverimg', models.ImageField(null=True, upload_to='movieimage', verbose_name='视频封面图片地址')),
                ('comment', models.CharField(max_length=200, verbose_name='摘要')),
                ('movie', models.FileField(null=True, upload_to='movie', verbose_name='视频地址')),
                ('pushdate', models.DateTimeField(auto_now=True, verbose_name='发布时间')),
                ('is_pub', models.BooleanField(choices=[(False, '否'), (True, '是')], default=False, verbose_name='是否立即发布')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='用户编号')),
                ('user_name', models.CharField(max_length=10, verbose_name='用户名')),
                ('user_password', models.CharField(max_length=200, verbose_name='密码')),
                ('user_realname', models.CharField(max_length=20, verbose_name='用户真实姓名')),
                ('user_phone', models.CharField(max_length=11, verbose_name='用户手机号')),
                ('user_qq', models.CharField(max_length=20, verbose_name='用户QQ号')),
                ('user_status', models.IntegerField(choices=[(0, '未登录'), (1, '已登录')], verbose_name='登录状态')),
                ('user_reg_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': 'APP用户',
                'verbose_name_plural': 'APP用户',
            },
        ),
        migrations.AddField(
            model_name='movie_opt_log',
            name='movie_id',
            field=models.ForeignKey(null=True, on_delete=False, to='api.movies', verbose_name='视频编号'),
        ),
        migrations.AddField(
            model_name='movie_opt_log',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=False, to='api.users', verbose_name='用户编号'),
        ),
        migrations.AddField(
            model_name='article_opt_log',
            name='article_id',
            field=models.ForeignKey(null=True, on_delete=False, to='api.articles', verbose_name='文章编号'),
        ),
        migrations.AddField(
            model_name='article_opt_log',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=False, to='api.users', verbose_name='用户编号'),
        ),
    ]
