# Generated by Django 2.0.6 on 2018-07-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('articlecoverimgurl', models.URLField(max_length=100)),
                ('comment', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('pushdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='moves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('movecoverimgurl', models.URLField(max_length=100)),
                ('comment', models.CharField(max_length=200)),
                ('moveurl', models.CharField(max_length=100)),
                ('pushdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
