# Generated by Django 2.0.6 on 2018-07-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('articlecoverimgurl', models.ImageField(null=True, upload_to='articleimage')),
                ('comment', models.CharField(max_length=200)),
                ('content', models.TextField(default='')),
                ('pushdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('moviecoverimgurl', models.ImageField(null=True, upload_to='movieimage')),
                ('comment', models.CharField(max_length=200)),
                ('movie', models.FileField(null=True, upload_to='movie')),
                ('pushdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
