# Generated by Django 2.0.6 on 2018-07-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='is_pub',
            field=models.BooleanField(choices=[(False, '否'), (True, '是')], default=True, verbose_name='是否立即发布'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='is_pub',
            field=models.BooleanField(choices=[(False, '否'), (True, '是')], default=True, verbose_name='是否立即发布'),
        ),
    ]
