# Generated by Django 2.0.6 on 2018-07-05 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='article_opt_log',
            fields=[
                ('art_opt_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='文章操作编号')),
                ('opt_content', models.CharField(max_length=400, null=True, verbose_name='操作内容')),
                ('opt_type', models.IntegerField(choices=[(1, '浏览'), (2, '关注')], null=True, verbose_name='操作类型')),
                ('opt_time', models.DateTimeField(auto_now=True, null=True, verbose_name='操作时间')),
                ('article_id', models.ForeignKey(null=True, on_delete=False, to='api.articles', verbose_name='文章编号')),
            ],
            options={
                'verbose_name': '文章操作记录',
                'verbose_name_plural': '文章操作记录',
            },
        ),
        migrations.RemoveField(
            model_name='articles_opt_log',
            name='article_id',
        ),
        migrations.RemoveField(
            model_name='articles_opt_log',
            name='user_id',
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'APP用户', 'verbose_name_plural': 'APP用户'},
        ),
        migrations.AddField(
            model_name='users',
            name='user_reg_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='注册时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='user_status',
            field=models.IntegerField(choices=[(0, '未登录'), (1, '已登录')], default=1, verbose_name='登录状态'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie_opt_log',
            name='opt_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='操作时间'),
        ),
        migrations.DeleteModel(
            name='articles_opt_log',
        ),
        migrations.AddField(
            model_name='article_opt_log',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=False, to='api.users', verbose_name='用户编号'),
        ),
    ]
