# Generated by Django 2.0.6 on 2018-07-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='articlecoverimgurl',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='moves',
            name='movecoverimgurl',
            field=models.CharField(max_length=100),
        ),
    ]
