# Generated by Django 2.0.6 on 2018-07-04 04:49

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=tinymce.models.HTMLField(max_length=20000, verbose_name='文章内容'),
        ),
    ]
