# Generated by Django 2.0.6 on 2018-07-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180703_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章s'},
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name': '视频', 'verbose_name_plural': '视频s'},
        ),
        migrations.AlterField(
            model_name='articles',
            name='articlecoverimg',
            field=models.ImageField(null=True, upload_to='articleimage', verbose_name='文章封面图片地址'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='author',
            field=models.CharField(max_length=20, verbose_name='文章作者'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='comment',
            field=models.CharField(max_length=200, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=models.TextField(default='', verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='pushdate',
            field=models.DateTimeField(auto_now=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=20, verbose_name='文章标题'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='author',
            field=models.CharField(max_length=20, verbose_name='视频作者'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='comment',
            field=models.CharField(max_length=200, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie',
            field=models.FileField(null=True, upload_to='movie', verbose_name='视频地址'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='moviecoverimg',
            field=models.ImageField(null=True, upload_to='movieimage', verbose_name='视频封面图片地址'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='pushdate',
            field=models.DateTimeField(auto_now=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(max_length=20, verbose_name='视频标题'),
        ),
    ]
