# Generated by Django 2.0.6 on 2018-07-05 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180705_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie_opt_log',
            options={'verbose_name': '视频操作记录', 'verbose_name_plural': '视频操作记录'},
        ),
    ]
