# Generated by Django 2.0.6 on 2018-07-03 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180703_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name': '视频', 'verbose_name_plural': '视频'},
        ),
    ]
